apiVersion: v1
kind: Service
metadata:
  name: gpu-monitor
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gpu-monitor
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
